// Lista compilada a partir de los diccionarios de glin-profanity (en, es, fr, de,
// it, pt) más groserías/insultos comunes en español mexicano que esos
// diccionarios no cubrían (ej. "pendejo", "puto", "chinga*"). Se filtraron
// entradas de 3 letras o menos y palabras de uso cotidiano que generaban
// falsos positivos (ej. "con", "comer", "negro", "martillo", "pistola") — ver
// notas de la sesión que agregó este archivo si hace falta ajustar la lista.
export const BANNED_USERNAME_WORDS: string[] = [
  "aborto", "acrotomophilia", "allupato", "ammucchiata", "anal", "anale", "analritter", "anilingus", "anus", "apeshit",
  "aranha", "ariano", "arrapato", "arrusa", "arruso", "arsch", "arschficker", "arschlecker", "arschloch", "arsehole",
  "asesinato", "asno", "assatanato", "asshat", "asshole", "assmunch", "asswipe", "autoerotic", "babeland", "bagascia",
  "bagassa", "bagnarsi", "baiser", "balalao", "baldracca", "balle", "bangbros", "bareback", "barenaked", "bastard",
  "bastardized", "bastardo", "bastinado", "battere", "battona", "bdsm", "beaner", "beaners", "belino", "bestiality",
  "bicha", "biga", "bigornette", "bimbo", "bimbos", "birdlock", "biscate", "bissexual", "bitch", "bitches",
  "bitte", "bloblos", "blowjob", "blumpkin", "bocchinara", "bocchino", "boceta", "bofilo", "boiata", "bollera",
  "bollocks", "bondage", "boner", "bonze", "boob", "boobs", "bordel", "bordello", "bosser", "bosta",
  "bourre", "bourree", "brackmard", "branlage", "branler", "branlette", "branleur", "branleuse", "bratze", "bucaiolo",
  "budiulo", "bukkake", "bulldyke", "bullshit", "bumbum", "bumsen", "bunghole", "burro", "busone", "busty",
  "butt", "buttcheeks", "butthole", "cabrao", "cabron", "cacca", "cacete", "caciocappella", "cadavere", "cagada",
  "cagadas", "cagar", "cagare", "cagata", "cagna", "cailler", "camgirl", "camisinha", "cammello", "camslut",
  "camwhore", "cappella", "caralho", "carciofo", "carpetmuncher", "casci", "cazzata", "cazzimma", "cazzo", "chatte",
  "checca", "chiappa", "chiasse", "chiavare", "chiavata", "chier", "chinga", "chingada", "chingadas", "chingadera",
  "chingaderas", "chingar", "chingas", "chiottes", "chochota", "chupada", "chupapollas", "chupar", "chupeton", "ciospo",
  "circlejerk", "clit", "clito", "clitoris", "clusterfuck", "cocaina", "cock", "cocks", "cocksucker", "coglione",
  "coglioni", "colhoes", "cona", "concha", "connard", "connasse", "conne", "cono", "consolo", "coon",
  "coons", "coprofagia", "coprolagnia", "coprophilia", "cornhole", "corno", "cornuto", "couilles", "cozza", "cramouille",
  "creampie", "culattina", "culattone", "culera", "culeras", "culero", "culeros", "culo", "cumming", "cunnilingus",
  "cunt", "darkie", "daterape", "deconne", "deconner", "deepthroat", "dendrophilia", "dick", "dildo", "dingleberries",
  "dingleberry", "dipshit", "ditalino", "dodel", "doggiestyle", "doggystyle", "dolcett", "domination", "dominatrix", "dommes",
  "drague", "dumbass", "dvda", "ecchi", "ejaculation", "emmerdant", "emmerder", "emmerdeur", "emmerdeuse", "encabronada",
  "encabronado", "encule", "enculee", "enculeur", "enculeurs", "enfoire", "enfoiree", "erotic", "erotism", "escort",
  "esperma", "esporra", "etron", "eunuch", "faggot", "fava", "fecal", "felch", "fellatio", "feltch",
  "femdom", "femminuccia", "fica", "fick", "ficken", "figa", "figging", "figone", "fingerbang", "fingering",
  "finocchio", "fisting", "flittchen", "foda", "foder", "follador", "follar", "folle", "footjob", "fottere",
  "fottersi", "fotze", "foutre", "fracicone", "fratze", "fregna", "frocio", "froscio", "frotting", "fuck",
  "fucker", "fuckface", "fuckin", "fucking", "fucktards", "fudgepacker", "futanari", "fvck", "genitals", "gerbe",
  "gilipichis", "gilipollas", "goatcx", "goatse", "gokkun", "goldone", "goodpoop", "goregasm", "gouine", "gozar",
  "grelho", "grilletto", "grogniasse", "grope", "guanto", "guardone", "gueule", "guro", "hackfresse", "handjob",
  "hardcore", "hentai", "heroina", "heterosexual", "hijaputa", "hijoputa", "homoerotic", "homoerotico", "homosexual", "honkey",
  "hooker", "humping", "hure", "hurensohn", "idiota", "imbecil", "incazzarsi", "incest", "incoglionirsi", "ingoio",
  "intercourse", "ische", "jackass", "jailbait", "jigaboo", "jiggaboo", "jiggerboo", "jilipollas", "jizz", "joto",
  "jotos", "jouir", "juggs", "kackbratze", "kacke", "kacken", "kackwurst", "kampflesbe", "kanake", "kapullo",
  "kimme", "kinbaku", "kinkster", "kinky", "knobbing", "lameculos", "leccaculo", "lecchino", "lesbica", "lmfao",
  "lofare", "loffa", "loffare", "lolita", "lovemaking", "lumaca", "lummel", "maciza", "macizorra", "maldito",
  "malpt", "mamada", "mamadas", "mames", "manico", "mannaggia", "marica", "maricon", "mariconazo", "masturbate",
  "merda", "merdata", "merde", "merdeuse", "merdeux", "merdoso", "meuf", "mierda", "mignotta", "milf",
  "minchia", "minchione", "montare", "mopse", "morgenlatte", "mose", "motherfucker", "muffdiving", "mufti",
  "muschi", "mussa", "naca", "nacas", "nackt", "naco", "nacos", "nambla", "nawashi", "nazi",
  "neonazi", "nerchia", "nigga", "nigger", "nimphomania", "nippel", "nipple", "nipples", "nude", "nudity",
  "nutte", "nympho", "nymphomania", "octopussy", "omfg", "omorashi", "onanieren", "orgasm", "orgasmus", "orgy",
  "padulo", "paedophile", "paki", "palle", "palloso", "palucher", "paneleiro", "panties", "panty", "patacca",
  "patonza", "pecorina", "pedale", "pedo", "pedobear", "pedophile", "pegging", "peidar", "pendeja", "pendejada",
  "pendejadas", "pendejo", "penis", "perra", "perras", "pervertido", "pesce", "peter", "pezon", "phuck",
  "picio", "pimmel", "pimpern", "pincare", "pinche", "pinkeln", "pipi", "pippone", "pirla", "pisciare",
  "piscio", "pisello", "pissed", "pissen", "pisser", "pissing", "pisspig", "pistolotto", "playboy", "pomiciare",
  "pompa", "pompino", "ponyplay", "poof", "poon", "poontang", "poopchute", "popel", "poppen", "porca",
  "porn", "porno", "pornography", "porra", "potta", "pouffiasse", "prostituta", "pthc", "pubes", "punany",
  "puppami", "pussy", "puta", "putada", "putain", "putazo", "pute", "puto", "putos", "puttana",
  "quaglia", "queaf", "queca", "queef", "racista", "raghead", "ramera", "ramoner", "rape", "raping",
  "rapist", "recchione", "rectum", "retard", "retarded", "reudig", "rimjob", "rimming", "rincoglionire", "rizzarsi",
  "rompiballe", "rosette", "ruffiano", "sacanagem", "sadico", "sadism", "salaud", "salope", "santorum", "sbattere",
  "sbattersi", "sborra", "sborrata", "sborrone", "sbrodolata", "scat", "schabracke", "scheisser", "schiesser", "schlampe",
  "schlong", "schnackeln", "schwanzlutscher", "schwuchtel", "scissoring", "scopare", "scopata", "scorreggiare", "sega", "semen",
  "sexo", "sexy", "shemale", "shibari", "shit", "shitblimp", "shithead", "shitshow", "shitty", "shota",
  "shrimping", "skeet", "slanteye", "slinguare", "slinguata", "slut", "smandrappata", "smut", "snatch", "snowballing",
  "soccia", "socmel", "sodomize", "sodomy", "soplagaitas", "soplapollas", "sorca", "spagnola", "spic", "splooge",
  "spompinare", "spooge", "spunk", "stfu", "sticchio", "strapon", "strappado", "stronza", "stronzata", "stronzo",
  "succhiami", "suce", "suck", "sucks", "sveltina", "sverginare", "swastika", "swinger", "tanche", "tapette",
  "tarzanello", "terrone", "tette", "teuch", "teuf", "threesome", "throating", "tirare", "tits", "tittchen",
  "titten", "titties", "titty", "topless", "torneira", "tosser", "towelhead", "tranny", "travesti", "tribadism",
  "tringler", "trique", "troia", "trombare", "troncher", "tubgirl", "turlute", "tushy", "twat", "twink",
  "twinkie", "uccello", "undressing", "upskirt", "urophilia", "vacca", "vaffanculo", "vagina", "vangare", "veado",
  "venire", "verga", "vergas", "veuve", "vibrador", "vibrator", "vogeln", "vollpfosten", "vorarephilia", "voyeur",
  "vulva", "wank", "wetback", "wichse", "wichsen", "wichser", "xana", "xochota", "yaoi", "yiffy",
  "zigounette", "zinne", "zizi", "zoccola", "zoophilia", "zorra", "zorras",
];
